# Generated by Django 4.0.4 on 2022-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(null=True)),
                ('name', models.TextField(blank=True, max_length=200)),
                ('file_no', models.IntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('dept', models.TextField(max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='Image')),
                ('no_fishes', models.IntegerField()),
                ('category', models.CharField(choices=[('small', 'small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50)),
                ('location', models.TextField(max_length=200, null=True)),
                ('about', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Image')),
                ('name', models.TextField(blank=True, max_length=200)),
                ('type', models.TextField(blank=True, max_length=200)),
                ('total', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harvested', models.IntegerField(null=True)),
                ('dam', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.TextField(blank=True, max_length=200)),
                ('dep_discription', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, max_length=200)),
                ('weight', models.IntegerField(blank=True)),
                ('amount', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=200)),
                ('last_name', models.TextField(blank=True, max_length=200)),
                ('salary', models.IntegerField(blank=True)),
                ('mobile', models.IntegerField(blank=True)),
                ('state', models.TextField(blank=True, max_length=200)),
                ('country', models.TextField(blank=True, max_length=200)),
                ('department', models.TextField(blank=True, max_length=200)),
                ('work_discription', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
