# Generated by Django 4.0.4 on 2022-06-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_dam_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit_sales',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
